"""added driver table

Revision ID: 2a0d1b9b21bf
Revises: 2ee70427d744
Create Date: 2025-11-25 11:25:48.567840

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0d1b9b21bf'
down_revision: Union[str, Sequence[str], None] = '2ee70427d744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = postgresql.ENUM(
    'APPROVED', 'REJECTED', 'WAITING',
    name='status',
    create_type=False
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_photo_url', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('license_photo_url', sa.String(), nullable=False),
    sa.Column('license_issued_at', sa.Date(), nullable=False),
    sa.Column('license_expires_at', sa.Date(), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_drivers_created_at'), 'drivers', ['created_at'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_updated_at'), 'drivers', ['updated_at'], unique=False)
    op.create_table('driver_company',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('driver_id', 'company_id')
    )
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.drop_table('driver_company')
    op.drop_index(op.f('ix_drivers_updated_at'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_created_at'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
