"""added rejection_reason to company table

Revision ID: 2ee70427d744
Revises: 2a4ba82ccc7e
Create Date: 2025-11-24 12:47:56.028940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee70427d744'
down_revision: Union[str, Sequence[str], None] = '2a4ba82ccc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'rejection_reason')
    # ### end Alembic commands ###
