"""added timestamps for secondary table driver company

Revision ID: 3ae5699f64d9
Revises: 2a0d1b9b21bf
Create Date: 2025-12-01 18:54:27.180888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae5699f64d9'
down_revision: Union[str, Sequence[str], None] = '2a0d1b9b21bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_company', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('driver_company', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_company', 'updated_at')
    op.drop_column('driver_company', 'created_at')
    # ### end Alembic commands ###
