"""added rejection reason for secondary table driver company

Revision ID: 453304db2f8a
Revises: 3ae5699f64d9
Create Date: 2025-12-02 12:27:06.731325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453304db2f8a'
down_revision: Union[str, Sequence[str], None] = '3ae5699f64d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_company', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_company', 'rejection_reason')
    # ### end Alembic commands ###
